env:
  CUDA_VISIBLE_DEVICES: "1"

args:
  #--input_a_path: "/data/WJH/03_SpinalKVEnhance/KV2SpineDataSet/Train/drr2_delete_nii"
  #--input_b_path: "/data/WJH/03_SpinalKVEnhance/KV2SpineDataSet/Train/drr_spine4_delete_nii"
  --input_a_path: "/data/WJH/03_SpinalKVEnhance/06_drr2spine_project/train/drr"
  --input_b_path: "/data/WJH/03_SpinalKVEnhance/06_drr2spine_project/train/spine"
  --checkpoints_dir: "/data/WJH/03_SpinalKVEnhance/06_drr2spine_project/checkpoints"
  --name: "One_ddr2spine_unet_lite_LPLS"
  --model: "cycle_gan"
  --netG: "unet_256_lite"
  --ngf: "48"
  --input_nc: "4"
  --output_nc: "1"
  --dataset_mode: "unaligned"
  --dataset_cache_file: "/data/WJH/03_SpinalKVEnhance/06_drr2spine_project/DRRSpinedataset_paths.pkl"
  --serial_batches: true
  --sample_ratio: "4"
  --sample_mode: "stride"
  --stride_tail_keep_below: "3"
  --preprocess: "none"
  --visuals_ext: "nii.gz"
  --num_threads: "16"
  --n_epochs: "300"
  --n_epochs_decay: "300"
  --batch_size: "1"
  --pool_size: "0"
  --print_freq: "1"
  --save_epoch_freq: "1"
  --max_dataset_size: "3000"
  --lambda_gan: "0.1"
  --lambda_L1_supervised: "50"
  --lambda_grad: "10"
  --lambda_laplacian: "3"
  --lambda_mean: "0"
  --gan_start_epoch: "20"
  --d_update_ratio: "1"
  --lr_D_scale: "1.0"
  # --continue_train: true
  # --epoch: "2200"
  # --epoch_count: "2201"
